#!/usr/bin/env python
import subprocess
import os
while True:
    gitadd = subprocess.check_output(["git", "add", "-A"])
    commit = subprocess.check_output(["git", "commit", "-m", "Update"])
    push = subprocess.check_output(["git", "push", "origin"])
    print "%s\n" % str(gitadd)
    print "%s\n" % str(commit)
    print "%s\n" % str(push)
    os.system("jekyll build")
    time.sleep(10)
