#!/usr/bin/env python
import subprocess
import os
import time
from datetime import datetime
now = str(datetime.now())
def clear():
    subprocess.call(["clear"])
while True:
    clear()
    print "Updating Website..."
    os.system("git add -A")
    os.system("git commit -m 'Update' -q")
    os.system("git push origin -q")
    os.system("jekyll build -q")
    print "\n\nWebsite Last Updated At: %s" % now
    time.sleep(30)
